# Generated by Django 5.1.3 on 2024-11-21 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('max_attendees', models.PositiveIntegerField(default=20)),
                ('students', models.ManyToManyField(blank=True, related_name='scheduled_trainings', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_instances', to='trainings.training')),
                ('waiting_list', models.ManyToManyField(blank=True, related_name='waiting_list_trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
