# Generated by Django 5.1.3 on 2024-12-04 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_duration'),
        ('trainings', '0004_alter_training_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_instances', to='trainings.training'),
        ),
    ]
