# Generated by Django 5.1.3 on 2024-12-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='training_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
