# Generated by Django 5.1.3 on 2024-11-17 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingschedule',
            name='duration',
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='picture',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
