# Generated by Django 5.1.3 on 2024-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attended_trainings',
            field=models.ManyToManyField(blank=True, related_name='attended_trainings', to='schedule.schedule'),
        ),
    ]
