# Generated by Django 5.1.3 on 2024-11-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_first_name_alter_appuser_last_name'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attended_trainings',
            field=models.ManyToManyField(blank=True, related_name='attended_trainings', to='trainings.trainingschedule'),
        ),
    ]
