# Generated by Django 5.1.3 on 2024-12-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='attendance_limit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_active',
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
    ]
