# Generated by Django 5.1.3 on 2024-12-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
